services:
  db:
    image: mariadb:11
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-rootpass}
      MARIADB_DATABASE: ${DB_NAME:-AA2_interfaces_DB}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: ngarre/backend-interfaces-aa2:3.0
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/${DB_NAME:-AA2_interfaces_DB}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME:-root}
      SPRING_DATASOURCE_PASSWORD: ${DB_ROOT_PASSWORD:-rootpass}
      JWT_SECRET: ${JWT_SECRET:-aa2_relab_2026_clave_super_larga_123456789}
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: .
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: http://localhost:8080
    


volumes:
  db_data:

  